/**
 * useSceneAudio — page-level singleton <audio> element with iOS gesture warmup.
 *
 * Why this exists: per-scene <audio> elements fail on iOS Safari. iOS grants
 * autoplay per-element, only to elements that started loading during a user
 * gesture. Mount a fresh <audio> on scroll-snap to a new scene → that element
 * never saw a gesture → .play() returns NotAllowedError silently. The previous
 * "globalUnlockAudio" boolean flag did NOT actually unlock anything on iOS — it
 * just remembered that a gesture happened.
 *
 * The fix: ONE <audio> element appended to <body> at first hook call. On the
 * very first user gesture, we play a tiny silent MP3 through it and immediately
 * pause. iOS marks that element as "user-activated" for the rest of the page
 * lifetime. All subsequent .src = … + .play() calls bypass the autoplay block,
 * regardless of which scene is being viewed.
 */
import { useCallback, useEffect, useRef, useState } from 'react'

// 12.5ms of WAV silence (mono, 16-bit, 8 kHz). Inlined so warmup never hits
// the network. Generated by a Python script — see the plan file. WAV is more
// reliably accepted by iOS Safari for the "any play() during a gesture
// permanently unlocks the element" trick than tiny MP3s, which can fail to
// decode in the small-frame edge case.
const SILENT_WAV_DATA_URI =
  'data:audio/wav;base64,UklGRuwAAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YcgAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAA=='

// Module-scoped singleton state. Persists across re-renders and component
// mount/unmount cycles. There can only be ONE of these on the page.
let singletonAudio: HTMLAudioElement | null = null
let isWarmed = false
let isWarming = false
let warmListenersInstalled = false
const warmedListeners = new Set<() => void>()
let currentSrc: string = ''
let currentSceneIndex: number = -1

function ensureSingleton(): HTMLAudioElement {
  if (singletonAudio) return singletonAudio
  if (typeof document === 'undefined') {
    // SSR / test stub — return a fake; calls will be no-ops until DOM exists.
    return {
      play: () => Promise.resolve(),
      pause: () => undefined,
      addEventListener: () => undefined,
    } as unknown as HTMLAudioElement
  }
  const el = document.createElement('audio')
  el.setAttribute('playsinline', '')
  el.preload = 'auto'
  el.style.display = 'none'
  document.body.appendChild(el)
  singletonAudio = el
  return el
}

async function warmup(): Promise<void> {
  if (isWarmed || isWarming) return
  isWarming = true
  const el = ensureSingleton()
  try {
    el.src = SILENT_WAV_DATA_URI
    el.muted = true
    await el.play()
    el.pause()
    el.currentTime = 0
    el.muted = false
    isWarmed = true
    warmedListeners.forEach((fn) => fn())
  } catch (err) {
    // Even if the silent play fails (some headless environments), don't block —
    // the next real play() attempt may still succeed if a gesture is ongoing.
    console.warn('[useSceneAudio] warmup play() failed:', err)
  } finally {
    isWarming = false
  }
}

function installWarmupListeners() {
  if (warmListenersInstalled || typeof window === 'undefined') return
  warmListenersInstalled = true
  const onGesture = () => {
    void warmup()
    if (isWarmed) {
      window.removeEventListener('pointerdown', onGesture, true)
      window.removeEventListener('touchstart', onGesture, true)
      window.removeEventListener('keydown', onGesture, true)
    }
  }
  window.addEventListener('pointerdown', onGesture, true)
  window.addEventListener('touchstart', onGesture, { capture: true, passive: true })
  window.addEventListener('keydown', onGesture, true)
}

export interface SceneAudioApi {
  /** Set src + .play() on the singleton. Idempotent for the same (src, sceneIndex). */
  playScene: (src: string, sceneIndex: number) => void
  /**
   * Pause the singleton — but ONLY if it is currently on `sceneIndex`'s audio.
   * Each SceneCard's "scrolled away" effect calls this with its own index, which
   * means a non-viewing scene whose audio just finished loading (and re-fired
   * its effect) cannot stop the audio of the scene the user is actually viewing.
   * Pass `undefined` to force-pause regardless of which scene is loaded.
   */
  pauseScene: (sceneIndex?: number) => void
  /** True after the first user gesture warmed the element. */
  isWarmed: boolean
}

export function useSceneAudio(): SceneAudioApi {
  // Subscribe to warmup state so consumers re-render when it changes (rare,
  // but lets components show "tap to enable sound" affordances if they want).
  const [warmedState, setWarmedState] = useState(isWarmed)

  // Lazy-install: first call ensures the singleton exists + the page-level
  // gesture listeners are installed. All subsequent calls are no-ops.
  useEffect(() => {
    ensureSingleton()
    installWarmupListeners()
    if (!isWarmed) {
      const handler = () => setWarmedState(true)
      warmedListeners.add(handler)
      return () => { warmedListeners.delete(handler) }
    }
  }, [])

  const playScene = useCallback((src: string, sceneIndex: number) => {
    if (!src) return
    const el = ensureSingleton()
    // Short-circuit: if we're already playing this exact scene's audio, leave it.
    if (currentSrc === src && currentSceneIndex === sceneIndex && !el.paused) return
    if (currentSrc !== src) {
      el.src = src
      el.currentTime = 0
      currentSrc = src
    }
    currentSceneIndex = sceneIndex
    el.muted = false
    el.play().then(() => {
      // A successful unmuted play proves the document is audio-unlocked, even
      // if the silent-WAV warmup never fired (e.g. on desktop, where the only
      // gesture the user gave was the click that landed them on the game page,
      // BEFORE this hook's listeners were installed). Notifying subscribers
      // here lets gates like SceneCard's video-unmute effect light up too,
      // restoring the pre-singleton-refactor desktop autoplay behaviour.
      if (!isWarmed) {
        isWarmed = true
        warmedListeners.forEach((fn) => fn())
      }
    }).catch((err: unknown) => {
      // Swallow autoplay rejections — the next gesture will warm us. Avoid
      // muting silently (the bug we used to have); the user wants narration,
      // not silent fallback.
      const e = err as { name?: string; message?: string }
      if (e?.name === 'NotAllowedError') {
        // Wait for a gesture; the warmup listeners will handle it. We don't
        // mute-fallback because TTS narration with no audio is just silence.
        return
      }
      // Wait for canplay then retry once (data URI / decode lag).
      const onCanPlay = () => {
        el.removeEventListener('canplay', onCanPlay)
        el.play().catch(() => undefined)
      }
      el.addEventListener('canplay', onCanPlay, { once: true })
    })
  }, [])

  const pauseScene = useCallback((sceneIndex?: number) => {
    const el = singletonAudio
    if (!el) return
    // Only the scene whose audio is actually loaded in the singleton may pause it.
    // Without this guard, a non-viewing scene's effect (re-firing because its
    // own audio just finished loading) would silence the scene the user IS
    // viewing. Force-pause is still possible by omitting the index.
    if (sceneIndex !== undefined && sceneIndex !== currentSceneIndex) return
    if (!el.paused) el.pause()
  }, [])

  return { playScene, pauseScene, isWarmed: warmedState }
}
